Add AWS CN  S3 support
freegroup/kube-s3 pull request #22
Opened 2022-06-08 03:52 UTC by panhaitao

Because aws-cn have to set env S3_URL, so I add some config list:  
1.   s3fs: add nonempt opts
2.  yaml/configmap: add S3_REGION S3_BUCKET S3_URL IAM_ROLE

2022-06-08 06:29 UTC, freegroup commented on Makefile
> +	docker push artifact.onwalk.net/k8s/kube-s3:latest
don't use your own docker repo in a public pull request.

2022-06-08 11:44 UTC, gaul requested changes

2022-06-08 11:44 UTC, gaul commented on docker-entrypoint.sh
> +  /usr/bin/s3fs ${S3_BUCKET} -o nonempty ${MNT_POINT} -d -d -f -o endpoint=${S3_REGION},iam_role=${IAM_ROLE},allow_other,retries=5 -o url=${S3_URL}
Why add `-o nonempty`?  Repeated above.

2022-06-08 11:44 UTC, gaul commented on docker-entrypoint.sh
> +  /usr/bin/s3fs -o nonempty ${S3_BUCKET} ${MNT_POINT} -d -d -f -o endpoint=${S3_REGION},allow_other,retries=5 -o url=${S3_URL}
s3fs will exit if `-o url` is provided but the value is empty:

```
s3fs: option url has invalid format, missing http / https protocol
```

2022-06-08 11:45 UTC, gaul commented
Is this a Google project?  Is the CLA required?  :confused:

2022-06-09 04:05 UTC, panhaitao commented on docker-entrypoint.sh
> +  /usr/bin/s3fs -o nonempty ${S3_BUCKET} ${MNT_POINT} -d -d -f -o endpoint=${S3_REGION},allow_other,retries=5 -o url=${S3_URL}
S3_URL is env
for axample: http://s3.cn-north-1.amazonaws.com.cn

2022-06-09 04:14 UTC, closed without merging

2022-06-09 04:15 UTC, panhaitao commented
I will Resubmit with CLA email

2022-06-09 14:08 UTC, gaul commented on docker-entrypoint.sh
> +  /usr/bin/s3fs -o nonempty ${S3_BUCKET} ${MNT_POINT} -d -d -f -o endpoint=${S3_REGION},allow_other,retries=5 -o url=${S3_URL}
If the user does not provide a value, which most do not, and thus the value is empty then s3fs will fail with the error.  Did you test this?